### ISSUE TITLE
observeAllT is not lazy in some monad transformer stacks

### ISSUE THREAD

**Issue by marklemay** [Bodigrim/logict#10]
for example,
```haskell
nats :: (MonadLogic m) =>  m Integer
nats = pure 0 `mplus` ((1 +) <$> nats)

ex0 :: [Integer]
ex0 = runIdentity $ observeManyT 20 nats
-- [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
ex1 :: [Integer]
ex1 = take 20 $ runIdentity $ observeAllT nats
-- [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

ex10 :: Either () [Integer]
ex10 = runIdentity $ runExceptT $ observeManyT 20 $ nats
-- Right [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
ex11 :: Either () [Integer]
ex11 = fmap (take 20) $ runIdentity $ runExceptT $ observeAllT nats
-- ...
```

If this is the intended behavior of `observeAllT` vs `observeManyT`, then a note should be added to the documentation.

**Comment by Bodigrim** [comment]
Agreed, a PR improving documentation would be much appreciated.

**Comment by marklemay** [comment]
Is this behavior implied by the types of the monad transformer stack?  I think it might be, since you have to look at every possibility to know that there is no `Left` constructor.

If this is implied by the types, the documentation about it probably shouldn't go in Haddock documentation on the function.   Where do you think it should go?  a new `Examples.hs`  or the existing `Test.hs`?

**Comment by Bodigrim** [comment]
From my point of view, this is an expected behaviour. Types drive `observeAllT` to collect all effects before returning any values of `a`. This is certainly impossible to do for an infinite number of values, except trivial case of `m ~ Identity`.
