### ISSUE TITLE
Add general conversion function

### ISSUE THREAD

**Issue by treeowl** [Bodigrim/logict#26]
We can write something vaguely like

```haskell
fromLogicT :: (Alternative (t m), MonadTrans t,...) => LogicT m a -> t m a
```

to convert from `LogicT` to another logic monad transformer. This can be implemented using a more general function accepting an arbitrary monad morphism:

```haskell
boingleT :: (Alternative n, ...) => (forall x. m x -> n x) -> LogicT m a -> n a
```

**Comment by Bodigrim** [comment]
I'm not opposed to this in principle, but which particular applications do you have in mind?

**Comment by treeowl** [comment]
Well, there are at least two other logic monads in the literature: the reflection without remorse one (currently being developed as `logict-sequence`) and the `ML` one I used for the `Traversable` instance (which was mentioned as prior art in the reflection without remorse paper; I don't remember who came up with it). Since we *can* offer such a general conversion function, I think we should.

**Comment by Bodigrim** [comment]
All right, go for it.
