### ISSUE TITLE
Can we get things like Pipes.Lift?

### ISSUE THREAD

**Issue by treeowl** [Bodigrim/logict#28]
For example, we might want

```haskell
runReaderL :: Monad m => e -> LogicT (ReaderT e m) a -> LogicT m a
```
Following types, this might look like

```haskell
runReaderL e (LogicT f) = LogicT $ \sk fk -> flip runReaderT e (f (\a r -> ReaderT $ \e' -> sk a (runReaderT r e')) (lift fk))
```

I'm just a *bit* worried about the appearance of both `e` and `e'`, given the challenges that showed up in the implementation of `local`. Are `e` and `e'` always the same? If not, which one do we want in the inner `runReaderT`, if either?

**Comment by Bodigrim** [comment]
I'd rather keep away from `local` trouble, unless you have a specific use-case.

**Comment by Bodigrim** [comment]
Before delving into interaction of `LogicT` and `ReaderT`, `mtl` leadership has to decide on `MonadReader` laws. Feel free to reopen, if it happens in our lifetime.
