### ISSUE TITLE
Not inferred as safe with ghc 7.10

### ISSUE THREAD

**Issue by feuerbach** [Bodigrim/logict#3]
For some reason ghc 7.10 stopped inferring `Control.Monad.Logic` as safe:

```
Test/SmallCheck/Property.hs:41:1:
    Control.Monad.Logic: Can't be safely imported!
    The module itself isn't safe.
```

(https://travis-ci.org/feuerbach/tasty/jobs/556618996)

Could you please look into it?

**Comment by Bodigrim** [comment]
This is weird. I have added `{-# LANGUAGE Safe #-}` to `Control.Monad.Logic` itself and it compiles fine: https://travis-ci.org/Bodigrim/logict/jobs/556938711

**Comment by feuerbach** [comment]
Yes, given this issue only shows up for a specific and old version of ghc, it's probably a compiler bug, so that doesn't sound surprising to me. I'll check whether this fixes the issue and report back.

**Comment by feuerbach** [comment]
Yep, that fixed it. A release would be much appreciated!
