### ISSUE TITLE
request for Hackage revision with `tasty` 1.5

### ISSUE THREAD

**Issue by peterbecich** [Bodigrim/logict#39]
I see the latest commit supports `tasty` 1.5.

I think the latest Hackage revision does not:
https://hackage.haskell.org/package/logict-0.8.1.0/src/logict.cabal
```
    tasty <1.5,
```

Can a new revision be published?
This helps build the library with Nix.

Thanks

**Comment by Bodigrim** [comment]
Done in https://hackage.haskell.org/package/logict-0.8.1.0/revisions/
