### ISSUE TITLE
Please new version release and publish to Hackage

### ISSUE THREAD

**Issue by ncaq** [Bodigrim/logict#41]
I submit pull request.
[feat: add `instance` for `MonadThrow` and `MonadCatch` by ncaq · Pull Request #37 · Bodigrim/logict](https://github.com/Bodigrim/logict/pull/37)
And merged 2023.

I'm afraid I have to ask for a release.

I have written a lot the following boilerplate.

``` hs
lift $ lift $ throwM NoPermission
```

I reconfirm that using GitHub's master commit I can write the following.

``` hs
throwM NoPermission
```

I can refer to the commit directly, but I still want to refer to the versioned version as much as possible.
I hope you will let me use this wonderful package conveniently.

**Comment by Bodigrim** [comment]
Done, thanks for the reminder: https://hackage.haskell.org/package/logict-0.8.2.0
