### ISSUE TITLE
remigrate to root on top of a darcs 2 git conversion?

### ISSUE THREAD

**Issue by cartazio** [Bodigrim/logict#6]
I've done it 1-2 times in the past

**Comment by Bodigrim** [comment]
My experience with darcs is very limited (in other words: non-existent :)
Is there a tool to convert or whatever?

**Comment by cartazio** [comment]
Yes,
I think actually Darcs itself has suport for emiting to git?

There’s a thing called darcs fast convert.

Googling around also points out
https://github.com/purcell/darcs-to-git. It’s readme indicates there’s some
tradeoffs between the two

I forget what I did when I migrated the language-c repo to git.

Would be good to do the right thing either way, at least for this repo.
(Fun fact: the soon to be old-random repo has a bunch of the base package
history in its prefix! )

**Comment by Bodigrim** [comment]
Done.

**Comment by cartazio** [comment]
yay!
for posterity https://hub.darcs.net/dolio/logict/changes is the source darcs repo : )
