### ISSUE TITLE
A lower level msplit?

### ISSUE THREAD

**Issue by Chobbes** [Bodigrim/logict#7]
I'm not sure if there's something that I'm missing, so apologies if this is a bad idea :).

Currently `msplit :: MonadLogic m => m a -> m (Maybe (a, m a))`. This is a little annoying, though, because the result of this is always wrapped in an `m`, and so there's no way to extract a value from `m a` by default. I understand this might be desirable --- maybe you don't want to expose a way of extracting an `a` from an `m a` or something...

But I can't help but feel like it would be really useful to have some sort of lower level `msplit` with the following type: `lsplit :: MonadLogic m => m a -> Maybe (a, m a)`. The advantage being that now you can essentially have `Foldable` for every instance of `MonadLogic` now... So, things like `observeAll` could be implemented generically, available for every instance of `MonadLogic`.

One reason why I think this might be doable is that it seems at first glance that `msplit` is always `return . lsplit`.

Any thoughts? Is there a reason why `msplit` returns a wrapped result? It currently doesn't make much sense to me (other than that it's convenient in do notation), because it seems like this split computation would have to extract something from the backtracking monad? Isn't that what you want it for? I could totally be wrong about this, and it would be greatly appreciated if you could help me understand :).

Thanks!

**Comment by Bodigrim** [comment]
I believe in general one cannot extract a pure `a` out of `m a`. AFAIU it would not be possible to define `lsplit` for something like `ReaderT Bool []`: 
https://github.com/Bodigrim/logict/blob/617990b88ced7256370f17473e025850b663051a/Control/Monad/Logic/Class.hs#L125-L129

**Comment by Chobbes** [comment]
Ah, of course you're right. I see now! Thanks for the quick explanation :).
