### ISSUE TITLE
Could use some examples

### ISSUE THREAD

**Issue by Soupstraw** [Bodigrim/logict#8]
The research paper is really dense, it would be great if there were some simple examples of how to use the monad.

**Comment by Bodigrim** [comment]
PRs improving documentation are always very welcome. Otherwise I'd appreciate more input about desirable examples.

**Comment by notooth1** [comment]
Can you convert this Prolog code to logict?

```
loves(vincent,mia).
loves(marcellus,mia).

jealous(A,B):- loves(A,C), loves(B,C).
```
and how to query:
```
loves(vincent,X).
jealous(vincent,marcellus).
```

**Comment by Bodigrim** [comment]
@notooth1 very similar to lists:

```haskell
{-# LANGUAGE MonadComprehensions, RebindableSyntax #-}

import Prelude hiding ((>>=))
import Control.Monad.Logic hiding ((>>=))

(>>=) :: MonadLogic m => m a -> (a -> m b) -> m b
(>>=) = (>>-)

-- Now actual code begins

data Person = Vincent | Mia | Marcellus
  deriving (Eq, Show)

loves :: MonadLogic m => m (Person, Person)
loves = msum $ map pure [(Vincent, Mia), (Marcellus, Mia)]

jealous :: MonadLogic m => m (Person, Person)
jealous = [ (a, b) | (a, c) <- loves, (b, c') <- loves, c == c' ]

queryLoves :: MonadLogic m => Person -> m Person
queryLoves a = [ b | (a', b) <- loves, a == a' ]

queryJealous :: MonadLogic m => Person -> Person -> m ()
queryJealous a b = [ () | (a', b') <- jealous, a == a', b == b' ]

-- > import Control.Monad.Logic
-- > observeAll jealous
-- [(Vincent,Vincent),(Marcellus,Vincent),(Vincent,Marcellus),(Marcellus,Marcellus)]
```

**Comment by Bodigrim** [comment]
Thanks to tireless efforts of @kquick, documentation is much better now. 
@Soupstraw @notooth1 @Kleidukos @ChrisPenner could you possibly take a look? Suggestions and comments would be highly appreciated.
Rendered haddocks are available at https://hackage.haskell.org/package/logict-0.7.1.0/candidate

**Comment by Kleidukos** [comment]
@Bodigrim Hi! Maybe `once` and `lnot` could benefit from examples as well?

**Comment by Soupstraw** [comment]
Certainly looks less intimidating now. To improve it further, it might be a good idea to add some concrete examples of how to use the functions and what they give. Basically something I could take a glimpse at and get the idea for what the function does.

See the [lens](https://hackage.haskell.org/package/lens-4.19.2/docs/Control-Lens-Prism.html#v:_Left) library documentation for example.

**Comment by ChrisPenner** [comment]
The docs look much better indeed 😄 

Just a few quibbles if you're looking for additional feedback:

* The [interleave](https://hackage.haskell.org/package/logict-0.7.1.0/candidate/docs/Control-Monad-Logic-Class.html#v:interleave) docs nicely explain **when** you'd use interleave; but they don't actually show an example of using it (and what the output would be).
* The [`Logic`](https://hackage.haskell.org/package/logict-0.7.1.0/candidate/docs/Control-Monad-Logic.html#t:Logic) type definition mentions it returns `a`'s; but there aren't any `a`'s in the definition. This one is pretty minor since folks probably know what it means.

Nice job everyone 😄

**Comment by Bodigrim** [comment]
Thanks all for feedback! Updated and uploaded at https://hackage.haskell.org/package/logict-0.7.1.0/candidate 
I'll release it by the end of the week.

**Comment by Bodigrim** [comment]
`logict-0.7.1.0` has been released. Thanks everyone involved!
